name = "designa-portfolio"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

[env.production]
name = "designa-portfolio"

[vars]
NODE_ENV = "production" 